settings:
  time_base: "_002"
  PDDN: false
  metric: "median"
  tissue_types: 
    - "WM"
    - "GM"
  polarimetric_parameters:
    - "linR"
    - "totD"
    - "azimuth_local_var"
    - "totP"
    - "azimuth"
  parameters_to_name:
    linR: "Linear retardance"
    totD: "Total diattenuation"
    azimuth_local_var: "Azimuth local variability"
    totP: "Total depolarization"
    azimuth: "Azimuth of the optical axis"

  instrument: "IMPV2"
  alignment_method: "MatchAnything_opencv"
  wavelength: 630nm
  shape_imgs:
    - 608
    - 512
  force_recompute: false

paths:
  base_path: "/home/elea/Documents/HORAO/PROJECTS/5_RIAP"
  data_path: ${paths.base_path}/data/impv2_dev
  output_path: ${paths.base_path}/output/IMPV2/
  output_alignement_folder: ${paths.base_path}/temp
  elastix_path: ${paths.base_path}/third_party/elastix
  elastix_binaries: ${paths.elastix_path}/elastix-5.2.0-linux
  superglue: ${paths.base_path}/third_party/superglue
  match_anything_path: ${paths.base_path}/third_party/MatchAnything
  fiji_path: ${paths.base_path}/third_party/Fiji.app/ImageJ-linux64

rois:
  max_number_of_random_squares: 40
  number_of_random_squares: 40
  square_size: 20
  square_number: 1
  type_rec_sq: "square"

histograms:
  linR: 
    borders: [0, 90]
    num_bins: 90
  totP:
    borders: [0, 1.1]
    num_bins: 80
  azimuth_local_var:
    borders: [0, 80]
    num_bins: 90
  totD:
    borders: [0, 0.5]
    num_bins: 50
  azimuth:
    borders: [0, 180]
    num_bins: 360

plot_limits:
  azimuth_local_var: [0, 50]
  azimuth_local_var_cv: [1, 3]
  linR: [0, 25]
  linR_cv: [0.4, 1]
  totP: [0.85, 1.0]
  totP_cv: [0.96, 1.04]
  totD: [0.020, 0.040]
  totD_cv: [0.9, 1.1]
  azimuth: [0, 180]
  azimuth_cv: [0, 60]
    
default_paths:
  polarimetry: "polarimetry_cam_registered/630_Image_Number_LQ/${settings.wavelength}"
  _50x50_images: "RIAP_results"

time_points:
  1: T0
  2: T1
  3: T2
  4: T3
  5: T4